[package]
name = "clicker"
version = { workspace = true }
authors = ["jercan_alex27@yahoo.com"]
edition = { workspace = true }
publish = false
license = { workspace = true }
homepage = "https://github.com/alexjercan/clicker-game-bevy"
description = "Clicker game where you try to collect as many resources."
categories = ["games"]

[lib]
name = "game"
path = "src/lib.rs"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true

[profile.dist]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
strip = true

[features]
default = []
debug = ["clicker_core/debug"]
dev = ["debug", "clicker_core/dev", "dep:clicker_probe"]

[dependencies]
clicker_core = { path = "crates/clicker_core" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4.5.48", features = ["derive"] }
clicker_probe = { path = "crates/clicker_probe", optional = true }

[dev-dependencies]
bevy.workspace = true
clicker_autopilot = { path = "crates/clicker_autopilot" }
clicker_probe = { path = "crates/clicker_probe" }
serde_json = "1.0.145"

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
bevy = "0.19.1"

[build-dependencies]
embed-resource = "3.0.6"
