[package]
name = "clicker_core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[features]
default = []
debug = ["dep:clicker_debug"]
dev = [
    "bevy/dynamic_linking",
    "bevy/trace",
    "debug",
    "dep:tracing-chrome",
    "dep:tracing-subscriber",
]

[dependencies]
bevy.workspace = true
clicker_animation = { path = "../clicker_animation" }
clicker_assets = { path = "../clicker_assets" }
clicker_audio = { path = "../clicker_audio" }
clicker_camera = { path = "../clicker_camera" }
clicker_debug = { path = "../clicker_debug", optional = true }
clicker_gameplay = { path = "../clicker_gameplay" }
clicker_particles = { path = "../clicker_particles" }
clicker_render = { path = "../clicker_render" }
clicker_state = { path = "../clicker_state" }
clicker_tile = { path = "../clicker_tile" }
clicker_ui = { path = "../clicker_ui" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-chrome = { version = "0.7.2", optional = true }
tracing-subscriber = { version = "0.3.20", optional = true }
